version: "2"

networks:
  zeebe_network:
    driver: bridge

volumes:
  zeebe_data:
  zeebe_elasticsearch_data:

services:
  zeebe:
    container_name: zeebe
    image: registry.ahanet.net:5000/zeebe:0.23.2
    environment:
      - ZEEBE_LOG_LEVEL=info
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ../lib/zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
  monitor:
    container_name: zeebe_monitor
    image: camunda/zeebe-simple-monitor:0.18.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.worker.hazelcast.connection=zeebe:5701
      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=demo
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    volumes:
    #  - ./simple-monitor-application.yaml:/usr/local/zeebe/config/application.yaml
      - ./postgresql-42.2.12.jar:/app/libs/postgresql-42.2.12.jar
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
  humantask:
    container_name: zeebe-simple-tasklist
    image: camunda/zeebe-simple-tasklist:latest
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8081:8081"
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://graylog.psamvp.hcs.harman.com:12201"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
  sftp:
    container_name: sftp-for-zeebe-demo
    image: atmoz/sftp
    volumes:
      - /var/zeebe-demo/sftp-upload:/home/ftpuser/upload
    ports:
      - "2222:22"
    command: ftpuser:ftppass:1001
    networks:
      - zeebe_network
  zeebe-worker:
    container_name: zeebe-worker
    image: 712823164894.dkr.ecr.us-east-2.amazonaws.com/psa-demo-zeebe-worker:121-master-6dcced1
    volumes:
      - /var/zeebe-demo/config:/usr/src/app/config
    environment:
      - ZEEBE_BROKER=zeebe:26500
      - ACTIVEMQ_HOST=activemq
      - SFTP_HOST=sftp:22
    depends_on:
      - zeebe
      - sftp
    logging:
      driver: gelf
      options:
        gelf-address: "tcp://graylog.psamvp.hcs.harman.com:12201"
    networks:
      - zeebe_network
  operate:
    container_name: operate
    image: camunda/operate:0.23.0
    ports:
      - "8083:8080"
    volumes:
      - ./operate.yml:/usr/local/operate/config/application.yml
    depends_on:
      - postgres
      - zeebe
    networks:
      - zeebe_network
#  activemq:
#    container_name: activemq-for-zeebe-demo
#    image: webcenter/activemq:latest
#    ports:
#      - "8161:8161"
#      - "61616:61616"
#      - "61613:61613"
#    environment:
#      - ACTIVEMQ_ADMIN_LOGIN=admin
#      - ACTIVEMQ_ADMIN_PASSWORD=password
##    volumes:
##      - /data/activemq:/data
##      - /var/log/activemq:/var/log/activemq
#    networks:
#      - zeebe_network
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ingress=[{"type":"append"},{"type":"bytes"},{"type":"convert"},{"type":"date"},{"type":"date_index_name"},{"type":"dissect"},{"type":"dot_expander"},{"type":"drop"},{"type":"fail"},{"type":"foreach"},{"type":"geoip"},{"type":"grok"},{"type":"gsub"},{"type":"join"},{"type":"json"},{"type":"kv"},{"type":"lowercase"},{"type":"pipeline"},{"type":"remove"},{"type":"rename"},{"type":"script"},{"type":"set"},{"type":"sort"},{"type":"split"},{"type":"trim"},{"type":"uppercase"},{"type":"urldecode"},{"type":"user_agent"}]
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - zeebe_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - zeebe_network
  kibana-gl:
    container_name: kibana-gl
    image: docker.elastic.co/kibana/kibana:6.8.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://graylog-es.psamvp.hcs.harman.com
      - LOGGING_VERBOSE=true
      # - XPACK_SECURITY_ENABLED=false
    networks:
      - zeebe_network
#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana-oss:6.7.1
#    ports:
#      - "5601:5601"
#    environment:
#      - LOGGING_VERBOSE=true
#    depends_on:
#      - elasticsearch
#    networks:
#      - zeebe_network
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - zeebe_network


